from csp.variables.ordering.var_ordering_strategy import VarOrderingStrategy

from csp.variables.ordering.default_var_order import DefaultVarOrder
from csp.variables.ordering.min_remaining_values import MinRemainingValues
